version: 0.0.{build}
branches:
  only:
  - master
  - development
  - appveyor
image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_depth: 1
build:
  verbosity: minimal
deploy: off
environment:
  steam_username:
    secure: kPfBMCQjIS7TuG8N78xUGw==
  steam_password:
    secure: 5L2WCCTom2qq75qIOEvujL4VqJWr10IRBzH6AwSQA9k=
install:
  - ps: .\before-build.ps1